import React from 'react';
import { Link } from 'react-router-dom';
import PageLayout from '../../components/PageLayout';

const ECGPage = () => {
    return (
        <PageLayout currentPage="services">
            {/* Hero Section */}
            <section className="hero">
                <div className="container">
                    <div className="fade-in" style={{ maxWidth: '800px', margin: '0 auto' }}>
                        <Link to="/services" style={{ color: 'var(--brand-red)', textDecoration: 'none', marginBottom: '15px', display: 'inline-block' }}>
                            ← Back to Services
                        </Link>
                        <span className="hero-label">Diagnostic Service</span>
                        <h2 className="hero-title" style={{ fontSize: '2.5rem' }}>Electrocardiogram (ECG)</h2>
                        <p className="hero-subtitle">
                            Also known as an electrocardiograph test
                        </p>
                    </div>
                </div>
            </section>

            {/* Content Section */}
            <section style={{ padding: '60px 0', background: 'var(--bg-white)' }}>
                <div className="container">
                    <div style={{ maxWidth: '900px', margin: '0 auto' }}>

                        {/* What is */}
                        <div className="fade-in" style={{ marginBottom: '50px' }}>
                            <h3 style={{ color: 'var(--brand-navy)', marginBottom: '20px', fontSize: '1.8rem' }}>
                                What is an ECG?
                            </h3>
                            <p style={{ fontSize: '1.05rem', lineHeight: '1.8', marginBottom: '20px' }}>
                                An ECG test records the electrical activity of the heart. It can inform doctors about heart rate, rhythm, conduction health of tissues, thickening of heart muscle, size of chambers, inflammation, ischemia (state of oxygen deprivation), heart attack (sudden blockage of blood supply to part of heart muscle), and a host of other important parameters.
                            </p>
                        </div>

                        {/* How it works */}
                        <div className="fade-in" style={{ marginBottom: '50px' }}>
                            <h3 style={{ color: 'var(--brand-navy)', marginBottom: '20px', fontSize: '1.8rem' }}>
                                How It Works
                            </h3>
                            <p style={{ fontSize: '1.05rem', lineHeight: '1.8', marginBottom: '20px' }}>
                                An ECG works by tracking the electrical impulses (or "waves") travelling through the heart with each heartbeat. This impulse starts in the right atrium (right upper chamber of the heart), generated by the heart's own independent "Pacemaker" and then travels throughout the heart tissue through a specialised highly sophisticated system of cells – just like "electrical wires". This electrical current causes the heart muscle to contract, squeeze and pump blood through the heart.
                            </p>
                            <p style={{ fontSize: '1.05rem', lineHeight: '1.8', marginBottom: '20px' }}>
                                A normal heartbeat on an ECG shows different waves that represent the heart's electrical activity. The first wave, called the "P wave," happens when the upper chambers (atria) send an electrical signal. After a brief pause, the signal reaches the lower chambers (ventricles), shown by the "QRS complex." This pause allows the upper chambers to push blood into the lower chambers before they contract to pump blood out. The last wave, the "T wave," shows the ventricles returning to their resting state. This cycle repeats with each heartbeat, occurring around 100,000 times per day in a healthy person.
                            </p>
                        </div>

                        {/* Preparing for your visit */}
                        <div className="fade-in" style={{ marginBottom: '50px' }}>
                            <h3 style={{ color: 'var(--brand-navy)', marginBottom: '20px', fontSize: '1.8rem' }}>
                                Preparing for Your Visit
                            </h3>
                            <h4 style={{ color: 'var(--brand-navy)', marginBottom: '15px' }}>What to Expect</h4>
                            <ul style={{ fontSize: '1.05rem', lineHeight: '1.9', paddingLeft: '30px', color: 'var(--text-main)' }}>
                                <li style={{ marginBottom: '12px' }}>For preparation, your skin will be cleaned with alcohol wipes and gently abraded with skin prep tape.</li>
                                <li style={{ marginBottom: '12px' }}>Please note that the patients will be required to remove their shirt above the waist for the procedure and you will be provided with a disposable gown.</li>
                                <li style={{ marginBottom: '12px' }}>For preparation, some hair may need to be shaved off to improve the electrical signals.</li>
                                <li style={{ marginBottom: '12px' }}>Electrodes are placed on your chest with a sticky, but easy-to-remove, adhesive. Lead wires from ECG machine are connected to the electrodes.</li>
                                <li style={{ marginBottom: '12px' }}>You'll be asked to lie still and breathe normally. Any movements can affect the reading.</li>
                                <li style={{ marginBottom: '12px' }}>Avoid wearing lotions or oils as they can interfere with electrode adhesion.</li>
                                <li style={{ marginBottom: '12px' }}>Avoid caffeine or stimulants for a few hours before the test as they can affect heart rhythm.</li>
                                <li style={{ marginBottom: '12px' }}>Please let the staff know if you have had any allergic reactions to the electrode adhesives previously.</li>
                            </ul>
                        </div>

                        {/* CTA Section */}
                        <div className="fade-in" style={{ marginTop: '60px', textAlign: 'center', padding: '40px', background: 'var(--brand-navy)', borderRadius: 'var(--radius-lg)' }}>
                            <h3 style={{ color: 'var(--bg-white)', marginBottom: '20px' }}>Ready to Book Your ECG?</h3>
                            <p style={{ color: 'var(--bg-white)', opacity: '0.9', marginBottom: '30px' }}>
                                Quick, simple, and non-invasive. Schedule your ECG today.
                            </p>
                            <Link to="/book" className="btn btn-primary">
                                Book Appointment
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
        </PageLayout>
    );
};

export default ECGPage;
